# Generated by Django 4.2.6 on 2023-11-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_postcategory_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choice',
            field=models.CharField(choices=[('NW', 'Новость'), ('AT', 'Статья')], default='AT', max_length=3),
        ),
    ]
